# Default values for dockerhub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: burdz/hello-dockerhub-manifest
  tag: dev
  pullPolicy: Always
service:
  name: hello-dockerhub-manifest
  type: NodePort
  externalPort: 8080
  internalPort: 8080
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
