apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-dockerhub-manifest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-dockerhub-manifest
    spec:
      containers:
      - name: hello-dockerhub-manifest
        image: burdz/hello-dockerhub-manifest:dev
        ports:
        - containerPort: 8080
