apiVersion: v1
kind: Service
metadata:
  name: hello-dockerhub-manifest
spec:
  type: NodePort
  selector:
    app: hello-dockerhub-manifest
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080